#ifndef _DEFINITIONS_H_DEFINED_
#define _DEFINITIONS_H_DEFINED_

#define SCREEN_WIDTH 1024
#define SCREEN_HEIGHT 768

#define MAX_KEYBOARD_KEYS 350

#define PLAYER_SPEED 5
#define PLAYER_SHOOT_SPEED 10

#define BULLETSPEED_PLAYER 16
#define BULLETSPEED_ENEMY 16

enum {
    BULLETTYPE_PLAYER,
    BULLETTYPE_ENEMY_COMMON
};

#endif