#ifndef _DEFINITIONS_H_DEFINED_
#define _DEFINITIONS_H_DEFINED_

#define SCREEN_WIDTH 1024
#define SCREEN_HEIGHT 768

#define MAX_KEYBOARD_KEYS 350

#define PLAYER_SPEED 5
#define PLAYER_RELOAD_SPEED 10

#define ENEMY_SPEED_COMMON 3

#define BULLETSPEED_PLAYER 16
#define BULLETSPEED_ENEMY 10

enum {
    BULLETTYPE_PLAYER,
    BULLETTYPE_ENEMY_COMMON,
    BULLETTYPE_ENEMY_FOLLOW
};

enum {
    ENEMYTYPE_COMMON,
    ENEMYTYPE_DIAGONAL
};

#endif